Repository GSA/plainlanguage.gov, pull requests merged in 2023-11, with the labels that each got.

#390 remove duplicate entry.
  _pages/guidelines/words/use-simple-words-phrases.md
Labels: content

#407 Update contacts.yml
  _data/contacts.yml
Labels: content

#404 Fix markdown in technical-terms-in-plain-english.md
  _pages/resources/humor/technical-terms-in-plain-english.md
Labels: bug, content

#415 POAM Nov 23
  package-lock.json
  package.json
Labels: dependencies
