Repository GSA/plainlanguage.gov, pull requests merged in 2024-02, with the labels that each got.

#417 Create codeql.yml
  .github/workflows/codeql.yml
Labels: dependencies, testing

#420 Update circleci ruby image
  .circleci/config.yml
Labels: dependencies

#423 Updating No FEAR Act link in footer
  _includes/components/footer.html
Labels: bug, dev
